### ISSUE TITLE
Unable to get Streetpasses

### ISSUE THREAD

**Issue by grantland** [mikechambers/pizone#3]
I've followed the instructions in the README, but I haven't seem to have gotten any Streetpasses. I did have some quirks while setting everything up, maybe that could be an issue?
- Using a different version of Node:

```
pi@raspberrypi ~ $ node -v
v5.5.0
```
- Was getting errors when setting up my RPi as an AP while starting `hostapd` with my wireless adapter, but got it working with [this](http://blog.sip2serve.com/post/48899893167/rtl8188-access-point-install-script) and I can now connect to the internet through it.
- I've turned off WiFi security (WPA2), in case that was required.
- I'm unable to add approved MAC addresses in Configuration.
- A quick error flashes and dissappears when the page reloads: "Oh Snap! You got an error! Something didn't go quite as expected. Make sure pizone is still running and try again."
- I used `raspberrypi` as the hostname instead of `pizone`.
- No weird logs:

```
pi@raspberrypi ~ $ tail -f /var/log/pizone
05/Feb/2016 07:02:87 +0000 - info: Stopping advanced IEEE 802.11 management: hostapd.
Starting advanced IEEE 802.11 management: hostapd.
05/Feb/2016 07:02:87 +0000 - info: Complete
05/Feb/2016 07:02:75 +0000 - info: Changing Access Point Information
05/Feb/2016 07:02:76 +0000 - info: HomePass Main : 4E:53:50:4F:4F:46 : attwifi
05/Feb/2016 07:02:33 +0000 - info: Stopping advanced IEEE 802.11 management: hostapd.
Starting advanced IEEE 802.11 management: hostapd.
05/Feb/2016 07:02:34 +0000 - info: Complete
Route request received : /getinfo
Route request received : /getaccessinfo
```

Would there be any other relevant information I could give?

**Comment by mikechambers** [comment]
If you connect to the access point using a laptop, can you get on the internet?

**Comment by grantland** [comment]
Yes, I can.

**Comment by mikechambers** [comment]
Can you ssh into your PI?
If so, check this file:
/etc/hostapd/hostapd.conf
and see what macaddr_acl is set to.
If it is 1, then you have to have the mac address included in: /etc/hostapd/hostapd.accept
I would first set it to 0 then restart hostapd:
/etc/init.d/hostapd
This should allow anyone to connect. This would tell you if that setting was keeping you from connecting.
If you can connect with it set to 0, set it back to 1, and then add your Mac address to the .accept file.

**Comment by grantland** [comment]
I can ssh in and `macaddr_acl` is set to 0. I'm not having problems connecting to it or the internet through it, but I am not getting any streetpasses. Should I start getting them immediately or after a few hours?

Also the web UI doesn't persist configuration changes for mac address restrictions, but I'm starting to think that it's not implemented yet?

**Comment by grantland** [comment]
I got it working. The mac address filtering problem was due to my wifi adapter not supporting that feature.

I'm not able to verify this, but I was also getting issues on Raspbian Jessie when setting up hostapd and udhcpd where I wasn't getting an IP address.

After redoing everything with a new wifi adapter and Raspbian Wheezy, it works now! Thanks for the awesome project!
